version: "3"

services:
  mydb:
    build: ./db
    image: mysql:latest

    restart: always

    environment:
      MYSQL_DATABASE: grocery_booking
      MYSQL_ROOT_PASSWORD: password

    ports:
      - "3306:3306"
    networks:
      - my-network

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MYSQL_HOST: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password

    depends_on:
      - mydb
    restart: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
