version: "3"

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: "grocery_booking"
      MYSQL_USER: "yug"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mysql

volumes:
  mysql-db:
